# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_payment_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('initial_payment_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=7)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount_per_cycle', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_cycle', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=125)),
                ('product_type', models.CharField(max_length=5)),
                ('charset', models.CharField(max_length=15)),
                ('currency_code', models.CharField(max_length=5)),
                ('custom', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('payer_email', models.EmailField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=255)),
                ('history', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('txn_type', models.CharField(max_length=250)),
                ('verify_sign', models.CharField(max_length=250)),
                ('profile_status', models.CharField(db_index=True, max_length=25)),
                ('notify_version', models.CharField(blank=True, max_length=10, null=True)),
                ('ipn_track_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
