# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0004_auto_20160811_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='recurringsubscription',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
