# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0005_auto_20160811_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscription',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
