# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0006_auto_20160811_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscription',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
