# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0007_auto_20160811_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscription',
            name='amount_per_cycle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='recurringsubscription',
            name='payment_cycle',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
