# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0008_auto_20160811_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringsubscription',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringsubscription',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
