# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0009_auto_20160811_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscription',
            name='ipn_track_id',
            field=models.CharField(blank=True, db_index=True, max_length=55, null=True),
        ),
    ]
