# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal_payments', '0010_auto_20160811_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_payment_id', models.CharField(blank=True, db_index=True, max_length=25, null=True, unique=True)),
                ('initial_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount_per_cycle', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payment_cycle', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(max_length=125)),
                ('product_type', models.CharField(max_length=5)),
                ('charset', models.CharField(max_length=15)),
                ('currency_code', models.CharField(max_length=5)),
                ('custom', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('payer_email', models.EmailField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=255)),
                ('receiver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=250, null=True)),
                ('subscr_id', models.CharField(blank=True, max_length=250, null=True)),
                ('txn_type', models.CharField(max_length=250)),
                ('verify_sign', models.CharField(max_length=250)),
                ('profile_status', models.CharField(db_index=True, max_length=25)),
                ('notify_version', models.CharField(blank=True, max_length=10, null=True)),
                ('ipn_track_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='RecurringSubscription',
            new_name='SubscriptionTxn',
        ),
    ]
