# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0011_auto_20160831_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprofile',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontxn',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
