# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0012_auto_20160907_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontxn',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paypal_payments.SubscriptionProfile'),
        ),
    ]
