# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0013_subscriptiontxn_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprofile',
            name='subscr_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
